### ISSUE TITLE
How to issue new client_id and client_secret?

### ISSUE THREAD

**Issue by cyantarek** [go2s/o2s#2]

**Comment by wongoo** [comment]
@cyantarek please provide more details，eg background, scenario, code sample, etc

**Comment by cyantarek** [comment]
In your code, you have used DemoClient and DemoUser for demo purpose. In o2/http/server.go

//DemoClient init demo client
func DemoClient(cs o2x.O2ClientStore) {
	err := cs.Set("000000", &o2m.Oauth2Client{
		ID:     "000000",
		Secret: "999999",
		Domain: "https://localhost",
		Scopes: []string{"manage", "admin", "view", "read"},
	})
	if err != nil {
		log.Printf("%v\n", err)
	}
}

//DemoUser init demo user
func DemoUser(us o2x.UserStore) {
	u := &o2x.SimpleUser{
		UserID: "u1",
		Scopes: map[string]string{
			"000000": "admin,manage",
		},
	}
	u.SetRawPassword("123456")
	u.Mobile = "13344556677"
	err := us.Save(u)
	if err != nil {
		glog.Infof("create demo user error: %v", err)
	}
}

But in production, there will be lots and lots of client for the OAuth2 server. So demo user won't work, we need a way to create new clients. But you have not mentioned how to create a new client.

**Comment by wongoo** [comment]
@cyantarek  As the demo, u can create a client through `ClientStore.Set()`, and create a user through `UserStore.Save()`. 
In production , server can create clients or users using the data submitted from a web form.

**Comment by cyantarek** [comment]
> In production , server can create clients or users using the data submitted from a web form.

How to do that? Especially the client creation part

**Comment by wongoo** [comment]
@cyantarek how to create client is a matter of busisness, I don't get what you means how to do that?

**Comment by cyantarek** [comment]
You said
> In production , server can create clients or users using the data submitted from a web form.

I want to know how can I add a handler so that I can create client?

For example, I want to add a handler that will set a new client and return it to the user. For this, I need a ClientStore instance. I can see there's one ClientStore in the main function of server.go
How can I use that inside o2/handler.go to add a new handler for creating clients?

Is it clear?

**Comment by cyantarek** [comment]
Ok, I did it. I've implemented Client creation endpoint and AuthorizationCode grant flow
